Add Create/Edit Fleet wizard
flightctl/flightctl-ui pull request #124
Opened 2024-04-30 12:12 UTC by rawagner

Depends on https://github.com/flightctl/flightctl-ui/pull/123

![Screenshot from 2024-04-30 14-10-12](https://github.com/flightctl/flightctl-ui/assets/2078045/b7014b8f-1930-41b9-a3d5-baef0b58d339)

![Screenshot from 2024-04-30 14-10-29](https://github.com/flightctl/flightctl-ui/assets/2078045/fbb11419-58e4-415b-99bd-5ba04ad2352c)

![Screenshot from 2024-04-30 14-11-25](https://github.com/flightctl/flightctl-ui/assets/2078045/8647c8ca-97df-473a-8c04-9ad4848bff22)

2024-05-02 10:20 UTC, celdrake commented on libs/ui-components/src/components/Fleet/CreateFleet/steps/ConfigTemplateForm.tsx
> +            <FormSelectOption value="secret" label={t('Kubernetes secret provider')} />
The kubernetes secrets config templates are currently not supported on the API.
We should hide them from the creation / edition forms, and we can keep the rest of the code that handles them.

2024-05-02 10:49 UTC, celdrake commented on libs/ui-components/src/components/Fleet/ImportFleetWizard/ImportFleetWizard.tsx
> +      <Button variant="secondary" onClick={goToPrevStep} isDisabled={isSubmitting || activeStep.id == repositoryStepId}>
Why add the "back" button for the first step? They are also not shown in Figma.

2024-05-03 09:01 UTC, celdrake commented on libs/ui-components/src/components/Fleet/CreateFleet/steps/ConfigTemplateForm.tsx
> +    <ExpandableSection
I discussed this with Nir, and we agreed that it would be better to show the config names for the collapsed element.

See in Figma section "Fleets_create fleet wizard 2".

Could you add this to this PR, or should we create a separate ticket?

2024-05-06 11:09 UTC, rawagner commented on libs/ui-components/src/components/Fleet/CreateFleet/steps/ConfigTemplateForm.tsx
> +    <ExpandableSection
the config is now shown in collapsed element

2024-05-06 11:10 UTC, rawagner commented on libs/ui-components/src/components/Fleet/ImportFleetWizard/ImportFleetWizard.tsx
> +      <Button variant="secondary" onClick={goToPrevStep} isDisabled={isSubmitting || activeStep.id == repositoryStepId}>
I would swear I saw it there..therefore I added it :) It is removed now.

2024-05-06 11:10 UTC, rawagner commented on libs/ui-components/src/components/Fleet/CreateFleet/steps/ConfigTemplateForm.tsx
> +            <FormSelectOption value="secret" label={t('Kubernetes secret provider')} />
Ok, the k8s secret option is now hidden

2024-05-06 11:11 UTC, rawagner commented on libs/ui-components/src/components/Fleet/CreateFleet/utils.ts
> +            targetRevision: Yup.string().required(t('Branch/tag/commit revision is required.')),
fixed

2024-05-06 11:12 UTC, rawagner commented on libs/ui-components/src/components/Fleet/CreateFleet/utils.ts
> +            mountPath: Yup.string().required(t('Mount path is required.')),
added absolute path validation + placeholder

2024-05-06 11:12 UTC, rawagner commented on libs/ui-components/src/components/Fleet/CreateFleet/steps/DeviceTemplateStep.tsx
> +            aria-label={t('OS image')}
should be fixed everywhere now

2024-05-06 11:13 UTC, rawagner commented on libs/ui-components/src/components/Fleet/CreateFleet/steps/ReviewStep.tsx
> +            <DescriptionListDescription>{values.osImage || '-'}</DescriptionListDescription>
Added the info text to review page

2024-05-06 11:14 UTC, rawagner commented on libs/ui-components/src/components/Fleet/CreateFleet/steps/ConfigTemplateForm.tsx
> +      <TextArea
I've added validation which also explains what format is expected

2024-05-06 11:14 UTC, rawagner commented on libs/ui-components/src/components/Fleet/CreateFleet/steps/ConfigTemplateForm.tsx
> +        <TextField aria-label={t('Path')} name={`configTemplates[${index}].path`} value={template.path} />
absolute path validation + placeholder added

2024-05-06 12:39 UTC, celdrake requested changes
Just a small issue with the warning about missing repositories

2024-05-06 12:39 UTC, celdrake commented on libs/ui-components/src/components/Fleet/CreateFleet/steps/ConfigTemplateForm.tsx
> +          {repositories.length && (
```suggestion
          {!repositories.length && (
```

FYI, Nir just added a new flow related to the Create fleet wizard. https://www.figma.com/file/85WfMxRxzyLEBUt3WYfzuh/Edge-management?type=design&node-id=3138-27622&mode=design&t=odDz0bzpV7nK5a7f-4

I created a separate [task](https://issues.redhat.com/browse/MGMT-17728), so for the scope of this PR it's perfect like this :+1:

2024-05-06 12:39 UTC, celdrake approved these changes

2024-05-06 12:56 UTC, merged