MGMT-17352 - Custom modal for deleting a fleet managed by a RS
flightctl/flightctl-ui pull request #125
Opened 2024-05-06 09:05 UTC by celdrake

- We will now allow to delete a fleet that is managed by a Resource sync.
 Prior to deleting the fleet, we will delete the resource sync as well.

- If the fleet is not managed by a Resource sync, there are no changes to the modal.
 
Message shown when the fleet is managed by a RS:
![show-warning](https://github.com/flightctl/flightctl-ui/assets/829045/6c897187-94e9-4f8a-9915-081e81b281da)

Message shown when the RS failed to load:
![cannot-delete](https://github.com/flightctl/flightctl-ui/assets/829045/98442e83-3f5c-4fe5-94c9-76a63a147969)

Message shown for an unmanaged fleet:
![unmanaged-fleet](https://github.com/flightctl/flightctl-ui/assets/829045/8922b6da-8c64-4048-9837-3591e653d9f5)

**Note**: Leaving as a Draft to avoid conflicts with the Create fleet wizard. I will rebase after the PR for the wizard is merged.

2024-05-06 11:40 UTC, rawagner requested changes

2024-05-06 11:40 UTC, rawagner commented on libs/ui-components/src/components/Fleet/DeleteFleetModal/DeleteFleetModal.tsx
> +        setError(
lets avoid storing JSX in react state.

Also it would be great to put a line break between text and `errorMsg`.


This comment applies for all other `setError` instances

2024-05-06 15:09 UTC, celdrake commented on libs/ui-components/src/components/Fleet/DeleteFleetModal/DeleteFleetModal.tsx
> +        setError(
Fixed now

2024-05-09 12:22 UTC, rawagner approved these changes

2024-05-09 12:22 UTC, merged