MGMT-17749 Always delete the repositories resource syncs
flightctl/flightctl-ui pull request #126
Opened 2024-05-06 10:36 UTC by celdrake

The modal for mass-deleting repositories shouldn't allow deleting the repositories without also deleting their associated resource syncs.

The UI will show a warning to indicate that the resource syncs will also be deleted, and it will list how many RSs there are in each of the selected repositories.

![delete-warning](https://github.com/flightctl/flightctl-ui/assets/829045/872c37fa-3c95-4509-a85e-90f15d332a38)

2024-05-09 12:24 UTC, rawagner requested changes

2024-05-09 13:07 UTC, celdrake commented on libs/ui-components/src/components/modals/massModals/MassDeleteRepositoryModal/MassDeleteRepositoryModal.tsx
> +        {isLoading && <>WAIT</>}
Actually, this was a reminder to implement the "loading" state but I missed it.
I added it now. (it will show a message and the "delete" button will be disabled)

2024-05-10 06:50 UTC, celdrake commented
I added a new commit to change the order of the actions for a device, so that it's first "edit labels", then "delete"
https://github.com/flightctl/flightctl-ui/pull/126/commits/036fdc0b4d6fd7c8f4e4b7445ed195a4ca89d5c7

Thanks to @mparram for the suggestion :)

2024-05-10 07:09 UTC, rawagner approved these changes

2024-05-10 07:10 UTC, merged