Leave Form Select empty if there are more options.
flightctl/flightctl-ui pull request #137
Opened 2024-05-13 07:36 UTC by rawagner

Show exclamation mark if there is an error in collapsed Fleet config

![Screenshot from 2024-05-13 09-33-15](https://github.com/flightctl/flightctl-ui/assets/2078045/975ec4f0-e567-4926-a855-e529df3a8279)

2024-05-13 09:06 UTC, celdrake requested changes

2024-05-13 09:06 UTC, celdrake commented on libs/ui-components/src/components/Fleet/CreateFleet/steps/ConfigTemplateForm.tsx
> +        setTouched(true);
When the user collapses the config item and opens it again, the form appears valid without error messages in the incomplete fields, because the parent field is touched, but not the nested fields.

IMO when the exclamation icon is shown and the config item is open, the form should show the section errors.

2024-05-14 08:03 UTC, rawagner commented on libs/ui-components/src/components/form/FormSelect.tsx
> +  }, [items]);
I've changed it to `error`

2024-05-14 08:04 UTC, rawagner commented on libs/ui-components/src/components/Fleet/CreateFleet/steps/ConfigTemplateForm.tsx
> +        setTouched(true);
OK, i've added code that will mark all failed fields as touched so that the error is shown.

2024-05-14 08:21 UTC, merged