Add EnrollmentRequest list and approval flow
flightctl/flightctl-ui pull request #18
Opened 2024-02-09 11:24 UTC by rawagner

![Screenshot from 2024-02-09 12-23-26](https://github.com/flightctl/flightctl-ui/assets/2078045/d2f764c1-1e71-476c-bf01-84ac819cbcae)
![Screenshot from 2024-02-09 12-23-48](https://github.com/flightctl/flightctl-ui/assets/2078045/7b8764ea-a241-42b3-b15e-0daf3f0f32c3)

2024-02-09 13:59 UTC, celdrake approved these changes
Works great!
Just a few small comments and questions

2024-02-09 13:59 UTC, celdrake commented on src/app/utils/status/enrollmentRequest.ts
> +  return 'Denied';
Could we get the condition  `Unknown` ? Shouldn't it be mapped to `Pending`?

2024-02-09 13:59 UTC, celdrake commented on src/app/components/EnrollmentRequest/EnrollmentRequestList.tsx
> +    !!filteredData && (
We can leave it as-is until we get new designs, but likely we'll need an empty state. Both for the general case, or when applying the filters.

2024-02-09 13:59 UTC, celdrake commented on src/app/components/EnrollmentRequest/EnrollmentRequestList.tsx
> +  const currentEnrollementRequest = erList?.items.find((er) => er.metadata.name === requestId);
small typo 
```suggestion
  const currentEnrollmentRequest = erList?.items.find((er) => er.metadata.name === requestId);
```

2024-02-09 13:59 UTC, celdrake commented on src/app/components/EnrollmentRequest/EnrollmentRequestList.tsx
> +  const [erList, loading, error, refetch] = useFetchPeriodically<EnrollmentRequestList>('enrollmentrequests');
The data appears to be sorted by ID which is not very useful.

We can do this later anyway, as we will also need pagination etc.

2024-02-12 08:22 UTC, rawagner commented on src/app/utils/status/enrollmentRequest.ts
> +  return 'Denied';
I'm not sure about mapping it to `Pending`. Lets mirror the API values for now, we will revisit later.

2024-02-12 08:22 UTC, rawagner commented on src/app/components/EnrollmentRequest/EnrollmentRequestList.tsx
> +  const currentEnrollementRequest = erList?.items.find((er) => er.metadata.name === requestId);
fixed!

2024-02-12 09:23 UTC, rawagner commented
I will be adding a route so that we can reference it via QR code

2024-02-13 11:43 UTC, celdrake requested changes

2024-02-13 11:43 UTC, celdrake commented on src/app/components/EnrollmentRequest/DeviceEnrollmentPage.tsx
> +  if (!loading) {
Probably left over for testing?

2024-02-13 11:43 UTC, celdrake commented on src/app/components/EnrollmentRequest/DeviceEnrollmentPage.tsx
> +  const [er, loading, error] = useFetchPeriodically<EnrollmentRequest>(`enrollmentrequests/${id}`);
We should check that the EnrollmentRequest is in a state that allows for it to be approved. 

Otherwise it throws an error 422 on the API, and it's not clear why that happens (I noticed by mistake as I copied an ID of an ER I had previously approved)

2024-02-13 12:37 UTC, rawagner commented on src/app/components/EnrollmentRequest/DeviceEnrollmentPage.tsx
> +  const [er, loading, error] = useFetchPeriodically<EnrollmentRequest>(`enrollmentrequests/${id}`);
Ok, I've added handling for a case when the request is already approved.
I'm not sure  what to do with  `Denied` state as ATM the we cannot deny the request (backend does not do anything when sending `approved: false`). So I do not have any specific handling for that case. We can revisit later.

2024-02-13 12:38 UTC, rawagner commented on src/app/components/EnrollmentRequest/DeviceEnrollmentPage.tsx
> +  if (!loading) {
yep! Good catch. fixed

2024-02-13 13:34 UTC, celdrake approved these changes

2024-02-13 13:35 UTC, merged