MGMT-16934 Highlight currently selected nav entry
flightctl/flightctl-ui pull request #29
Opened 2024-02-15 15:45 UTC by celdrake

Highlights the entries of the menu based on the current location

2024-02-16 07:12 UTC, rawagner commented
If I go to details (ie Fleet Details), the Fleet NavItem stops being highlighted

2024-02-22 13:05 UTC, rawagner requested changes
works fine!
Lets address my concerns about the css rules & location before merging

2024-02-22 13:05 UTC, rawagner commented on src/app/components/AppLayout/AppToolbar.css
> +}
These should go to `AppNavigation.css` file


We should also scope these css changes to under some `fctl` component to make sure we wont override some other parts of the app (especially when we will integrate into other products..even though, our Navigation wont appear there..but still, i'd just make sure to scope these changes)

2024-02-22 13:51 UTC, celdrake commented on src/app/components/AppLayout/AppToolbar.css
> +}
Good suggestions, I agree with both. I'll update the MR

2024-02-22 14:07 UTC, rawagner approved these changes

2024-02-22 14:38 UTC, merged