Resource syncs pages
flightctl/flightctl-ui pull request #32
Opened 2024-02-21 15:11 UTC by celdrake

Will add details later.

2024-02-26 07:36 UTC, rawagner requested changes

2024-02-26 07:36 UTC, rawagner commented on app.js
> +const buildUrl = (resource, query) => {
lets do this in frontend code

2024-02-26 07:36 UTC, rawagner commented on src/app/components/Repository/RepositoryDetails.tsx
> +  const { repositoryId } = useParams() as { repositoryId: string };
```suggestion
  const { repositoryId } = useParams<{ repositoryId: string }>();
```

2024-02-26 07:36 UTC, rawagner commented on src/app/components/ResourceSync/RepositoryResourceSyncList.tsx
> +  const [rsList, , , refetch] = useFetchPeriodically<ResourceSyncList>({
Im missing loading/error state handling

2024-02-26 09:13 UTC, celdrake commented on src/app/components/Repository/RepositoryDetails.tsx
> +  const { repositoryId } = useParams() as { repositoryId: string };
The definition of `useParams` allows for `string | undefined` , so this suggestion is not equivalent.
With it, on line 106 we would have to cast `repositoryId`, or provide a fallback for it.

2024-02-26 09:13 UTC, celdrake commented on src/app/components/ResourceSync/RepositoryResourceSyncList.tsx
> +  const [rsList, , , refetch] = useFetchPeriodically<ResourceSyncList>({
I'm adding a basic handling of both.

2024-02-26 09:31 UTC, rawagner commented on src/app/components/Repository/RepositoryDetails.tsx
> +  const { repositoryId } = useParams() as { repositoryId: string };
oh, that's a shame :/

2024-02-26 14:48 UTC, celdrake commented on app.js
> +const buildUrl = (resource, query) => {
Checked after rebasing, and the query using `labelSelector` works fine with the new Go proxy, no need for these adaptations anymore.

2024-02-27 07:29 UTC, rawagner approved these changes

2024-02-27 07:29 UTC, merged