MGMT-17185: Keep RS modal open if creation fails
flightctl/flightctl-ui pull request #69
Opened 2024-03-14 09:28 UTC by celdrake

When the creation of a RS fails, the error is ignored and the form is closed.

- Before submitting the form, we'll verify if the name is unique. If it isn't, the form won't be submitted and a user-riendly error will be shown.
![rs-duplicate](https://github.com/flightctl/flightctl-ui/assets/829045/12424a02-4244-4a3c-b0fd-95d02b1773eb)

- In case of an error, we'll keep the form open and show the error returned by the backend.
![rs-be-error](https://github.com/flightctl/flightctl-ui/assets/829045/79d7f2d5-419a-4b10-a1be-a39ce9f11258)

(For testing it, you can remove the checking if the name is duplicate, and see that the error returned by the backend is shown.)

2024-03-14 09:29 UTC, celdrake commented on src/app/components/ResourceSync/CreateResourceSync/CreateRepositoryResourceSync.tsx
> -  const formSubmit = async () => {
This was unnecessary as the form submit is now disabled when the form is invalid

2024-03-14 14:58 UTC, rawagner commented on src/app/components/ResourceSync/CreateResourceSync/CreateRepositoryResourceSync.tsx
> +        }
Why do we need this ? Is the msg from backend that bad ? :) Maybe they could improve ?

2024-03-14 15:14 UTC, celdrake commented on src/app/components/ResourceSync/CreateResourceSync/CreateRepositoryResourceSync.tsx
> +        }
Since we are querying the API to check if a RS exists with the same name, the error 404 means the name is available for the new RS that will be created, and we should not show the error.

2024-03-14 15:17 UTC, rawagner commented on src/app/components/ResourceSync/CreateResourceSync/CreateRepositoryResourceSync.tsx
> +        }
sure, but why we dont just attempt to create and show the error from backend ? 

Why do we need to check ourselves by doing the GET request & show our custom msg ?

2024-03-14 15:44 UTC, celdrake commented on src/app/components/ResourceSync/CreateResourceSync/CreateRepositoryResourceSync.tsx
> +        }
Sorry I misunderstood.

IMO t would be slightly more use-friendly to avoid submitting an invalid form and provide a more customised message. 

The Backend just changed the error from the previous 500 to an error 400 (https://github.com/flightctl/flightctl/pull/169)
![message](https://github.com/flightctl/flightctl-ui/assets/829045/11c438f8-8da4-4250-a814-7bc1ab6431cd)

I'll remove the logic prior to attempting to create the RS, and fix the message parsing

2024-03-15 06:44 UTC, rawagner requested changes

2024-03-15 06:44 UTC, rawagner commented on src/app/components/ResourceSync/CreateResourceSync/CreateRepositoryResourceSync.tsx
> +  const [error, setError] = React.useState<string | React.ReactNode>();
leftover
```suggestion
  const [error, setError] = React.useState<string>();
```

2024-03-15 06:53 UTC, celdrake commented on src/app/components/ResourceSync/CreateResourceSync/CreateRepositoryResourceSync.tsx
> +  const [error, setError] = React.useState<string | React.ReactNode>();
True, changed back.

2024-03-15 06:56 UTC, rawagner approved these changes

2024-03-15 06:56 UTC, merged