MGMT-17176 warn about repo deletion
flightctl/flightctl-ui pull request #72
Opened 2024-03-14 16:34 UTC by celdrake

We should warn users when they delete a repository which as resourcesyncs, about whether they also want to delete the resourcesyncs or not. 

Users can choose to:
1. Delete the Repository and RSs --> any fleet that was being synced from the RS will become unmanaged.
2. Delete only the Repository --> The RSs become unlinked (they wouldn't be visible from the UI in that case)

I chose to create a custom modal since this flow is much different that the general case. Plus we don't have a design for this section of the UI, and it's very likely that the design will have an impact on the current behaviour.

Note: Marking as Draft as I included changes from https://github.com/flightctl/flightctl-ui/pull/69, and I'll rebase one that MR is merged.

2024-03-18 07:29 UTC, rawagner requested changes

2024-03-18 07:29 UTC, rawagner commented on src/app/components/Repository/RepositoryDetails/RepositoryCustomDeleteModal.tsx
> +        // Fallback to the case without resourcesyncs, to allow the user to attempt deleting the repository
IMO it would be better to inform user that an error occurred (give them the exact msg) and maybe let them pick if they want to delete repo only or try to refetch

2024-03-18 07:29 UTC, rawagner commented on src/app/components/Repository/RepositoryDetails/RepositoryCustomDeleteModal.tsx
> +  const deleteAction = async (actionName: string) => {
```suggestion
  const deleteAction = async (actionName: 'repoAndRSs' | 'repoOnly') => {
```

2024-03-18 07:29 UTC, rawagner commented on src/app/components/Repository/RepositoryDetails/RepositoryCustomDeleteModal.tsx
> +      <Button
we should add `isLoading` too

2024-03-18 07:29 UTC, rawagner commented on src/app/components/Repository/RepositoryDetails/RepositoryDetails.tsx
> +  const onDelete = async () => {
```suggestion
  const onDelete = () => {
```

2024-03-18 09:34 UTC, celdrake commented on src/app/components/Repository/RepositoryDetails/RepositoryCustomDeleteModal.tsx
> +        // Fallback to the case without resourcesyncs, to allow the user to attempt deleting the repository
We're now showing the error and warning the user that they would not delete the resourcesyncs.

2024-03-18 09:36 UTC, celdrake commented on src/app/components/Repository/RepositoryDetails/RepositoryCustomDeleteModal.tsx
> +      <Button
Added back.
Since we're showing a general spinner I thought it would be too much. But we can keep it for for consistency.

2024-03-18 09:36 UTC, celdrake commented
I forgot to show the same modal from the RepositoryList page. I've now also added it there.

2024-03-19 08:33 UTC, rawagner approved these changes

2024-03-19 08:33 UTC, merged