i18n all strings
flightctl/flightctl-ui pull request #98
Opened 2024-04-09 11:52 UTC by rawagner

2024-04-10 07:57 UTC, celdrake requested changes
I noted a few missing labels.

2024-04-10 07:57 UTC, celdrake commented on src/app/components/DetailsPage/DetailsNotFound.tsx
> +            We couldn&apos;t find the fleet with id <strong>{id}</strong>
I'm wondering if we should avoid using the `&apos;`?
Maybe we could rephrase as "could not" to avoid it?

2024-04-10 07:57 UTC, celdrake commented on src/app/components/Device/AddDeviceModal/AddDeviceModal.tsx
>                    <FormGroup label="Disk URL">
```suggestion
                  <FormGroup label={t('Disk URL')}>
```

label missing i18n.

2024-04-10 07:57 UTC, celdrake commented on src/app/components/Repository/RepositoryList.tsx
> +    <ResourceListEmptyState icon={RepositoryIcon} titleText="No repositories here!">
Needs i18n.
```suggestion
    <ResourceListEmptyState icon={RepositoryIcon} titleText="No repositories here!">
```

2024-04-10 07:57 UTC, celdrake commented on src/app/components/Device/DeviceList.tsx
> +    <ResourceListEmptyState icon={MicrochipIcon} titleText="No devices here!">
Needs i18n. (same for the fleets empty state)

2024-04-11 08:04 UTC, rawagner commented on src/app/components/DetailsPage/DetailsNotFound.tsx
> +            We couldn&apos;t find the fleet with id <strong>{id}</strong>
Rephrased all occurrences or `&apos;`

2024-04-11 08:16 UTC, celdrake commented on locales/en/translation.json
> +  "We couldn not find the fleet with id <1>{id}</1>": "We couldn not find the fleet with id <1>{id}</1>",
There's a couple typos of `couldn not`
```suggestion
  "We could not find the fleet with id <1>{id}</1>": "We could not find the fleet with id <1>{id}</1>",
```

2024-04-11 08:16 UTC, celdrake approved these changes

2024-04-11 08:32 UTC, rawagner commented on locales/en/translation.json
> +  "We couldn not find the fleet with id <1>{id}</1>": "We couldn not find the fleet with id <1>{id}</1>",
great catch. Fixed.

2024-04-11 09:03 UTC, merged